// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSearchFunctionTGDDTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSearchFunctionTGDD() {
    driver.get("https://www.thegioididong.com/");
    driver.manage().window().setSize(new Dimension(619, 831));
    driver.findElement(By.id("skw")).click();
    driver.findElement(By.id("skw")).sendKeys("iphone14");
    driver.findElement(By.id("skw")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(1) > a > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".media-slider")).click();
    driver.findElement(By.cssSelector(".media-slider")).click();
    driver.findElement(By.cssSelector(".media-slider")).click();
    driver.findElement(By.cssSelector(".item:nth-child(1) .ls-is-cached")).click();
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.cssSelector("h1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.cssSelector(".main-menu > .active")).click();
    driver.findElement(By.cssSelector(".main-menu > .active")).click();
    driver.findElement(By.cssSelector(".main-menu > .active")).click();
    driver.findElement(By.cssSelector(".breadcrumb > li:nth-child(1) > a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box-quicklink__item:nth-child(10)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".q-manu > .box-quicklink__item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".main-menu > li:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".main-menu > li:nth-child(2)")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > a > span")).click();
    driver.findElement(By.cssSelector(".main-menu > .active")).click();
    driver.findElement(By.cssSelector(".main-menu > .active")).click();
    driver.findElement(By.cssSelector(".active > a > span")).click();
    driver.findElement(By.cssSelector(".main-menu > li:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".active i > img")).click();
    driver.findElement(By.cssSelector(".box-quicklink__item:nth-child(1) > .no-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(1) > a > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,560)");
    driver.findElement(By.cssSelector(".item:nth-child(6) .item-img")).click();
    js.executeScript("window.scrollTo(0,89.5999984741211)");
    {
      WebElement element = driver.findElement(By.cssSelector(".campaign-option"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
